---
   - name: incl vars
     include_vars: ./vlans.yml
     connection: local
   - name: Create a new file
     file: path=../results/{{ jira }} state=directory
     connection: local
   - name: Create a new file
     file: path=../results/{{ jira }}/{{ inventory_hostname }}conf state=touch
     connection: local
   - name: run extremefacts module to get extreme facts
     debug: msg= "System {{ inventory_hostname }} {{ jira }}"
     connection: local
   - name: update networkfile
     connection: local
     template: src=/etc/ansible/roles/addvlanpod10/template/network.txt.j2 dest=../results/{{ jira }}/{{ inventory_hostname }}conf
 #  - name: enter prompt
 #    vars_prompt:
#       - name: "network pod"
#         prompt: "Which network pod are your vlans?"
#   - name: prompt to continue
#     pause: prompt='EAPS mode requires confirmation when applying config Please confirm ,  Press return to continue. Press Ctrl+c and then "a" to abort'
   - name: Address Information
     prompt:
       msg:
         - say: "First Name:"
           ask: first_name
        # - say: "Hello {{ first_name }}!  What's your favorite color?"
         #  ask: color
